// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from "@lezer/lr";

import { cqlHighlighting } from "./highlight";
import { descendant, identifiers, js, newlines } from "./lezer-tokens";
export const parser = LRParser.deserialize({
  version: 14,
  states:
    "2YQ]QfOOPwOSOOO|QeO'#CgOOQT'#Cf'#CfO!nQfO'#ClOOQT'#Cn'#CnO!vQfO'#CqO#[QeO'#CdO!vQfO'#CtOOQT'#Dx'#DxOOQU'#Cw'#CwO#yQfO'#CvOOQU'#Dc'#DcO$XQfO'#DbO$dQdO'#DwOOQS'#Dw'#DwO$xQdO'#CcOOQU'#Cb'#CbOOQU'#Dk'#DkQ]QfOOP%QOdO'#DvPOOO)C?j)C?jO%`QtO'#DyOOQT'#Ch'#ChOOQT,59R,59ROOQT,59W,59WOOQT,59[,59[OOQT,59],59]O!vQfO,59]O!vQfO,59_O!vQfO,59`OOQT,59`,59`OOQS'#D{'#D{OOQS'#Cz'#CzO#yQfO'#C{O%eQdO'#CyOOQS'#Dz'#DzO%yQdO,59bOOQS'#De'#DeO&[QdO,59|O'RQdO'#C|OOQS'#Dl'#DlOOQS'#Dn'#DnO'YQlO'#DaO'bQdO'#DfO'hQdO'#DfOOQS'#Df'#DfOOQS,5:c,5:cOOQU,58},58}OOQU-E7i-E7iPOOO,5:b,5:bP'sOSO,5:bP'{OdO,5:bO(WQdO,5:eOOQT1G.w1G.wOOQT1G.y1G.yOOQT1G.z1G.zOOQS,59g,59gO#yQfO,59gO(]QdO'#C|O(kQdO1G.|O(|QtO'#D]OOQS1G.|1G.|O(qQdO1G.|O)[QdO1G/hOOQS1G/h1G/hO)bQdO1G/hO)mQdO'#DOOOQS,59h,59hOOQS'#DQ'#DQOOQS,59k,59kOOQS'#DT'#DTO*RQdO,59nOOQS'#DZ'#DZO*WQdO,59tOOQS'#Dh'#DhOOQS'#Di'#DiOOQS,5:R,5:ROOQS,5:U,5:UOOQS-E7j-E7jOOQS,59{,59{O&mQdO'#C|OOQS-E7l-E7lOOQS,5:Q,5:QO*]QdO,5:QPOOO1G/|1G/|P*hOSO1G/|OOQT1G0P1G0POOQS1G/R1G/ROOQS7+$h7+$hO*pQdO7+$hO*{QdO'#D^O+WQtO'#D^OOQS'#D^'#D^O+fQdO'#ESOOQS,59w,59wO+nQdO,59wOOQS7+%S7+%SO+sQdO7+%SOOQS,59j,59jO,OQtO1G/YO,TQdO1G/`OOQS1G/l1G/lPOOO7+%h7+%hOOQS<<HS<<HSO,YQtO,59xO,hQtO,59xO,]QdO,59xO,sQtO,5:nO-RQdO,5:nOOQS1G/c1G/cOOQS<<Hn<<HnO-ZQdO'#DVO-^QdO'#DVOOQS'#DV'#DVO-fQdO7+$tO-kQdO7+$zO-pQtO1G/dO-{QdO1G/dOOQS1G/d1G/dOOQS,5:X,5:XO.WQtO1G0YOOQS-E7k-E7kO.fQtO,59sOOQS,59r,59rOOQS<<H`<<H`OOQS<<Hf<<HfOOQS7+%O7+%OO.kQtO7+%OP.vQtO'#DmOOQS1G/_1G/_OOQS<<Hj<<Hj",
  stateData:
    "/R~O!iOSSOS!fPQ~OPQOXXOaSOcTOfUOiWOlYO!W[O~O!fdO~O]fOfZXiZXlZXqZX!WZX!dZX!eZX!gZX!wZX~OPQOcjO~OPQOXXOaSOcTOfUOiWO~OflOinO!dmOlWXqWX!WWX!eWX!gWX!wWX~OPpOXpOcpOirO~OPvOXvOcvO~OlYOqxO!W[O!w{O!e!kX!g!kX~O!e!QO!g!QO~OS!TO!e!SO!g!SO!i!UO~O^!VO~Oi![O]mXqmX!emX!gmX!wmX~O]!_Oq!]O!w{O!eja!gja~O]!_Oq!]O!w{O!e!Ua!g!Ua~O!p!eO!r!gO!s!iO!u!kO!x!mO!y!nO~O]!_O~P&mOQ!rOR!rO~O]!_Oq!sO!w{O!e!YX!g!YX~O!e!wO!g!wO~OS!xO!e!wO!g!wO~O_!yO~O!p!eO!r!gO!s!iO!u!kO~O]!_Oq!]O!w{O!eji!gji~O^!}O_#ROq#OO!R#PO~O]!_Oq!]O!w{O!e!Ui!g!Ui~O!q#VO]rXqrX!erX!grX!wrX~Ox#WO~Ox#XO~O!w{O!e!Ya!g!Ya~O!e#ZO!g#ZO~O!w{O!ejq!gjq~Oq#]O_!QX!S!QX~O^#_Oq#^O_!QX!S!QX~O!S#`O_!vX~O_#bO~O!w{O!e!Uq!g!Uq~O^#dO~O!O#hO~O^#jOq#iO_!Qa!S!Qa~O^#kO_!Qa!S!Qa~O^!}Oq#OO!R#PO_!va~O!S#mO_!va~Oa#oO!t#pOuyX~Ou#qO~Ou#rO~O^#sO_!Qi!S!Qi~Oq#tO_!Qi!S!Qi~O^!}Oq#OO!R#PO_!vi~O^#vO~O^#wO_!Qq!S!Qq~O^!}Oq#OO!R#PO~O",
  goto: "(Y!wPPPPPP!x!|#QP#U#_#kPPP#UP#UP#U#UP#U#UP#n#uP#z#}#}$SP$[$S$aP$S$fP$k$n$q$S$tP$y%]PP%e#n&TP&Y#r&]&a&a&e&h&n&|'SPPPPPPP'Y']'a't'w(QPPPPPP(VTbOcTaOcT^Oc_XOUWclmn^ROUWclmnRiSRhQS_OcR!P^VZO^cRuZVtZr![]y^uw|!^!bV!fx!]!sV!hx!]!sV!jx!]!sR#g#WR#f#WR#e#WV!lx!]!sQ!auQ!dwQ!pxQ!v|Q!|!^R#U!bQ#Q!_V#l#`#m#uQ!O^Q!`uQ!cwS!u|}S!{!^!aS#T!b!dQ#Y!vQ#[!|R#c#UV]O^cRw]Tz^|T!ox!sR}^QcOR!RcSz^|Q!^uQ!bwT!q!^!bQ#a#QR#n#aQ|^R!t|RePT`OcSVOcQkUQoWQ!WlQ!XmR!YnRgQQsZQ!ZrR!z![VqZr![R#S!_",
  nodeNames:
    "⚠ Identifier JsBlock JsStatement Comment Script Statement SelectorLine ModuleSelector UniversalSelector NameSelector IndexableIdentifier Index [ Integer ] TypeSelector . RegExpNameSelector RegExp RegExpTypeSelector ChildSelector ChildOp DescendantSelector SiblingSelector SiblingOp OpSpec OpSentinel @ OpSelector NameSelector SiblingSelector GradientFacet : GradientFacetIdent NormFacet NormFacetIdent ) ScaleFacet ScaleFacetIdent ( ScaleArg Percent Float LabelFacet LabelFacetIdent String Slice SliceItem Ellipsis , JsPipe ParamSpec ParamSentinel # ParamName ModuleSpec ModuleFacet ModuleSelectInput ModuleSelectOutput SliceMod",
  maxTerm: 87,
  nodeProps: [
    ["isolate", 4, ""],
    ["closedBy", 13, "]"],
    ["openedBy", 15, "["],
  ],
  propSources: [cqlHighlighting],
  skippedNodes: [0, 4],
  repeatNodeCount: 4,
  tokenData:
    "1l~RnXY#P[]#Ppq#Prs#kst%cuv%hwx%mxy'`yz'ez{'j{|'o|}(Y}!O(S!O!P(_!P!Q(r!Q!['w![!],k!`!a,p!b!c,}!}#O-S#O#P#b#P#Q-X#Z#[-^#]#^-u#`#a.x#b#c/g#c#d0O#g#h0s#p#q1b#r#s1g~#US!i~XY#P[]#Ppq#P#O#P#b~#eQYZ#P]^#P~#pW!O~OY#kZr#krs$Ys#O#k#O#P$_#P;'S#k;'S;=`%]<%lO#k~$_O!O~~$bRO;'S#k;'S;=`$k;=`O#k~$pX!O~OY#kZr#krs$Ys#O#k#O#P$_#P;'S#k;'S;=`%];=`<%l#k<%lO#k~%`P;=`<%l#k~%hO!W~~%mO!t~~%rW!O~OY%mZw%mwx$Yx#O%m#O#P&[#P;'S%m;'S;=`'Y<%lO%m~&_RO;'S%m;'S;=`&h;=`O%m~&mX!O~OY%mZw%mwx$Yx#O%m#O#P&[#P;'S%m;'S;=`'Y;=`<%l%m<%lO%m~']P;=`<%l%m~'eOx~~'jOu~~'oOX~R'tPiP!Q!['wQ'|Q^Q!Q!['w#R#S(SQ(VP!Q!['w~(_O!S~R(dPaP!O!P(gQ(jP!O!P(mQ(rO!RQ~(uXOY)bZ!P)b!P!Q,P!Q!})b!}#O*k#O#P+j#P;'S)b;'S;=`+y<%lO)b~)gXc~OY)bZ!P)b!P!Q*S!Q!})b!}#O*k#O#P+j#P;'S)b;'S;=`+y<%lO)b~*XUc~#Z#[*S#]#^*S#a#b*S#g#h*S#i#j*S#m#n*S~*nVOY*kZ#O*k#O#P+T#P#Q)b#Q;'S*k;'S;=`+d<%lO*k~+WSOY*kZ;'S*k;'S;=`+d<%lO*k~+gP;=`<%l*k~+mSOY)bZ;'S)b;'S;=`+y<%lO)b~+|P;=`<%l)b~,UTS~OY,PZ],P^;'S,P;'S;=`,e<%lO,P~,hP;=`<%l,P~,pOq~~,uPf~!`!a,x~,}Of~~-SOl~~-XO]~~-^O_~~-aP#f#g-d~-gP#T#U-j~-mP#W#X-p~-uO!p~~-xQ#X#Y.O#b#c.a~.RP#b#c.U~.XP#h#i.[~.aO!q~~.dP#d#e.g~.jP#i#j.m~.pP#h#i.s~.xO!x~~.{P#T#U/O~/RP#U#V/U~/XP#X#Y/[~/_P#`#a/b~/gO!u~~/jP#c#d/m~/pP#f#g/s~/vP#a#b/y~0OO!r~~0RP#i#j0U~0XP#h#i0[~0_P#d#e0b~0eP#i#j0h~0kP#h#i0n~0sO!y~~0vP#V#W0y~0|P#T#U1P~1SP#`#a1V~1YP#X#Y1]~1bO!s~~1gO!w~P1lOiP",
  tokenizers: [descendant, identifiers, newlines, js, 0, 1],
  topRules: { Script: [0, 5] },
  tokenPrec: 0,
});
